### ISSUE TITLE
Bug when parsing Organization

### ISSUE THREAD

**Issue by teolemon** [linclark/MicrodataPHP#5]
I'm getting a "Catchable fatal error: Object of class stdClass could not be converted to string in …"
when MicrodataPHP starts parsing the Organization markup.
My guess is that it's because Organization has itself several properties.
I'm not very skilled, so I'm unsure whether it's a bug or working as intended, and I'm just not using the right syntax.

```
<?php
  ini_set('display_errors', 'On');
  require('MicrodataPhp.php');
  $md = new MicrodataPhp($_GET['url']);
  $data = $md->obj();
print "<b><br>Work Hours&nbsp;:</b>&nbsp;";
  print $data->items[0]->properties['workHours'][0];
print "<b><br>Hiring Organization&nbsp;:</b>&nbsp;";
  print $data->items[0]->properties['hiringOrganization'][0];
print "<b><br>jobLocation&nbsp;:</b>&nbsp;";
print $data->items[0]->properties['jobLocation'][0];
?>
```

**Comment by linclark** [comment]
Can you post the HTML that you are trying to parse?

**Comment by teolemon** [comment]
For instance, this job offer: 
http://candidat.pole-emploi.fr/candidat/rechercheoffres/detail/014YXXK

**Comment by linclark** [comment]
You kind of figured out the problem yourself. It is because the Organization is an object with properties, not a string itself. To access the string values of the Organization, you just keep chaining until you get to the property which has a string value

For example:

```
$data->items[0]->properties['hiringOrganization'][0]->properties['name'][0];
```

Since this isn't something related to microdata specifically, but instead is about how you work with data structures in PHP, I'd suggest asking on StackOverflow if you have more questions about it.

**Comment by teolemon** [comment]
Thanks so much Lin. I got educated, as you suggested :-)

**Comment by linclark** [comment]
You're welcome, good luck :)
